export const defaultRoster = [
  // --- RAW (MALE) ---
  { name: 'CM Punk', brand: 'Raw', overall: 94, isHeel: false },
  { name: 'Seth Rollins', brand: 'Raw', overall: 94, isHeel: false },
  { name: 'Gunther', brand: 'Raw', overall: 93, isHeel: true },
  { name: 'Jey Uso', brand: 'Raw', overall: 91, isHeel: false },
  { name: 'Bron Breakker', brand: 'Raw', overall: 90, isHeel: true },
  { name: 'Logan Paul', brand: 'Raw', overall: 90, isHeel: true },
  { name: 'LA Knight', brand: 'Raw', overall: 89, isHeel: false },
  { name: 'AJ Styles', brand: 'Raw', overall: 88, isHeel: true },
  { name: 'Bronson Reed', brand: 'Raw', overall: 88, isHeel: true },
  { name: 'Finn Bálor', brand: 'Raw', overall: 88, isHeel: true },
  { name: 'Dominik Mysterio', brand: 'Raw', overall: 87, isHeel: true },
  { name: 'Jimmy Uso', brand: 'Raw', overall: 86, isHeel: false },
  { name: 'Sheamus', brand: 'Raw', overall: 86, isHeel: false },
  { name: 'Rey Mysterio', brand: 'Raw', overall: 85, isHeel: false },
  { name: 'Kofi Kingston', brand: 'Raw', overall: 83, isHeel: false },
  { name: 'Rusev', brand: 'Raw', overall: 83, isHeel: true },
  { name: 'Austin Theory', brand: 'Raw', overall: 82, isHeel: true },
  { name: 'Xavier Woods', brand: 'Raw', overall: 82, isHeel: false },
  { name: 'Chad Gable', brand: 'Raw', overall: 81, isHeel: true },
  { name: 'Pat McAfee', brand: 'Raw', overall: 80, isHeel: false },
  { name: 'Dragon Lee', brand: 'Raw', overall: 79, isHeel: false },
  { name: 'Ivar', brand: 'Raw', overall: 79, isHeel: true },
  { name: 'JD McDonagh', brand: 'Raw', overall: 79, isHeel: true },
  { name: 'Je\'Von Evans', brand: 'Raw', overall: 78, isHeel: false },
  { name: 'Ludwig Kaiser', brand: 'Raw', overall: 77, isHeel: true },
  { name: 'Otis', brand: 'Raw', overall: 75, isHeel: false },
  { name: 'Akira Tozawa', brand: 'Raw', overall: 68, isHeel: false },

  // --- SMACKDOWN (MALE) ---
  { name: 'Cody Rhodes', brand: 'SmackDown', overall: 95, isHeel: false },
  { name: 'Roman Reigns', brand: 'SmackDown', overall: 95, isHeel: false },
  { name: 'Drew McIntyre', brand: 'SmackDown', overall: 93, isHeel: true },
  { name: 'Randy Orton', brand: 'SmackDown', overall: 92, isHeel: false },
  { name: 'Sami Zayn', brand: 'SmackDown', overall: 89, isHeel: false },
  { name: 'Jacob Fatu', brand: 'SmackDown', overall: 88, isHeel: true },
  { name: 'Damian Priest', brand: 'SmackDown', overall: 87, isHeel: false },
  { name: 'Kevin Owens', brand: 'SmackDown', overall: 87, isHeel: false },
  { name: 'Uncle Howdy', brand: 'SmackDown', overall: 87, isHeel: true },
  { name: 'Shinsuke Nakamura', brand: 'SmackDown', overall: 86, isHeel: true },
  { name: 'Solo Sikoa', brand: 'SmackDown', overall: 85, isHeel: true },
  { name: 'Ilja Dragunov', brand: 'SmackDown', overall: 85, isHeel: false },
  { name: 'Carmelo Hayes', brand: 'SmackDown', overall: 84, isHeel: true },
  { name: 'Trick Williams', brand: 'SmackDown', overall: 84, isHeel: false },
  { name: 'Tama Tonga', brand: 'SmackDown', overall: 83, isHeel: true },
  { name: 'Joe Gacy', brand: 'SmackDown', overall: 82, isHeel: true },
  { name: 'Alex Shelley', brand: 'SmackDown', overall: 80, isHeel: false },
  { name: 'Chris Sabin', brand: 'SmackDown', overall: 80, isHeel: false },
  { name: 'Erick Rowan', brand: 'SmackDown', overall: 80, isHeel: true },
  { name: 'Montez Ford', brand: 'SmackDown', overall: 80, isHeel: false },
  { name: 'The Miz', brand: 'SmackDown', overall: 80, isHeel: true },
  { name: 'Tonga Loa', brand: 'SmackDown', overall: 79, isHeel: true },
  { name: 'Angelo Dawkins', brand: 'SmackDown', overall: 78, isHeel: false },
  { name: 'Rey Fenix', brand: 'SmackDown', overall: 78, isHeel: false },
  { name: 'Talla Tonga', brand: 'SmackDown', overall: 77, isHeel: true },
  { name: 'Tommaso Ciampa', brand: 'SmackDown', overall: 77, isHeel: false },
  { name: 'Johnny Gargano', brand: 'SmackDown', overall: 76, isHeel: false },
  { name: 'Santos Escobar', brand: 'SmackDown', overall: 76, isHeel: true },
  { name: 'Axiom', brand: 'SmackDown', overall: 75, isHeel: false },

  // --- NXT (MALE) ---
  { name: 'Oba Femi', brand: 'NXT', overall: 85, isHeel: true },
  { name: 'Ethan Page', brand: 'NXT', overall: 83, isHeel: true },
  { name: 'Joe Hendry', brand: 'NXT', overall: 80, isHeel: false },
  { name: 'Tony D\'Angelo', brand: 'NXT', overall: 79, isHeel: false },
  { name: 'Hank Walker', brand: 'NXT', overall: 77, isHeel: false },
  { name: 'Tank Ledger', brand: 'NXT', overall: 77, isHeel: false },
  { name: 'Nathan Frazer', brand: 'NXT', overall: 76, isHeel: false },
  { name: 'Charlie Dempsey', brand: 'NXT', overall: 75, isHeel: true },
  { name: 'Lexis King', brand: 'NXT', overall: 74, isHeel: true },
  { name: 'Andre Chase', brand: 'NXT', overall: 73, isHeel: false },

  // --- RAW (FEMALE) ---
  { name: 'Rhea Ripley', brand: 'Raw', overall: 96, isHeel: false },
  { name: 'Becky Lynch', brand: 'Raw', overall: 94, isHeel: false },
  { name: 'IYO SKY', brand: 'Raw', overall: 93, isHeel: true },
  { name: 'Liv Morgan', brand: 'Raw', overall: 92, isHeel: true },
  { name: 'Naomi', brand: 'Raw', overall: 92, isHeel: false },
  { name: 'Stephanie Vaquer', brand: 'Raw', overall: 92, isHeel: true },
  { name: 'Asuka', brand: 'Raw', overall: 91, isHeel: true },
  { name: 'Bayley', brand: 'Raw', overall: 89, isHeel: false },
  { name: 'Nikki Bella', brand: 'Raw', overall: 88, isHeel: false },
  { name: 'Natalya', brand: 'Raw', overall: 86, isHeel: false },
  { name: 'Raquel Rodriguez', brand: 'Raw', overall: 86, isHeel: true },
  { name: 'Roxanne Perez', brand: 'Raw', overall: 85, isHeel: true },
  { name: 'Kairi Sane', brand: 'Raw', overall: 84, isHeel: true },
  { name: 'Lyra Valkyria', brand: 'Raw', overall: 84, isHeel: false },
  { name: 'Zoey Stark', brand: 'Raw', overall: 80, isHeel: true },

  // --- SMACKDOWN (FEMALE) ---
  { name: 'Bianca Belair', brand: 'SmackDown', overall: 94, isHeel: false },
  { name: 'Charlotte Flair', brand: 'SmackDown', overall: 93, isHeel: true },
  { name: 'Tiffany Stratton', brand: 'SmackDown', overall: 91, isHeel: true },
  { name: 'Jade Cargill', brand: 'SmackDown', overall: 88, isHeel: false },
  { name: 'Nia Jax', brand: 'SmackDown', overall: 88, isHeel: true },
  { name: 'Alexa Bliss', brand: 'SmackDown', overall: 87, isHeel: false },
  { name: 'Giulia', brand: 'SmackDown', overall: 86, isHeel: false },
  { name: 'Chelsea Green', brand: 'SmackDown', overall: 85, isHeel: true },
  { name: 'Zelina', brand: 'SmackDown', overall: 83, isHeel: false },
  { name: 'Jordynne Grace', brand: 'SmackDown', overall: 81, isHeel: false },
  { name: 'Lash Legend', brand: 'SmackDown', overall: 81, isHeel: true },

  // --- LEGENDS / SPECIAL ---
  { name: 'Elite Roman Reigns', brand: 'Legend', overall: 97, isHeel: true },
  { name: 'John Cena', brand: 'Legend', overall: 97, isHeel: false },
  { name: 'Stone Cold Steve Austin', brand: 'Legend', overall: 97, isHeel: false },
  { name: 'Elite Undertaker', brand: 'Legend', overall: 96, isHeel: false },
  { name: 'The Rock \'01', brand: 'Legend', overall: 96, isHeel: false },
  { name: 'The Rock', brand: 'Legend', overall: 95, isHeel: true },
  { name: 'Brock Lesnar', brand: 'Legend', overall: 94, isHeel: true },
  { name: 'Hulk Hogan', brand: 'Legend', overall: 94, isHeel: false },
  { name: 'Shawn Michaels', brand: 'Legend', overall: 94, isHeel: false },
  { name: 'Bret Hart', brand: 'Legend', overall: 93, isHeel: false },
  { name: 'Mark Henry', brand: 'Legend', overall: 92, isHeel: false },
  { name: 'Triple H', brand: 'Legend', overall: 91, isHeel: true },
  { name: 'Eddie Guerrero', brand: 'Legend', overall: 90, isHeel: false },
  { name: 'Chyna', brand: 'Legend', overall: 88, isHeel: false },
  { name: 'El Hijo del Vikingo', brand: 'AAA', overall: 86, isHeel: false },
  { name: 'Abyss', brand: 'Legend', overall: 85, isHeel: true },
  { name: 'Penta', brand: 'Raw', overall: 84, isHeel: false },
];